name: Deploy Next.js to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup environment variables
      run: |
        echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL || 'https://margarita215729.github.io/truck-repair-assistant' }}" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_BASE_PATH=${{ secrets.NEXT_PUBLIC_BASE_PATH || '/truck-repair-assistant' }}" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_NOMINATIM_URL=${{ secrets.NEXT_PUBLIC_NOMINATIM_URL || 'https://nominatim.openstreetmap.org' }}" >> $GITHUB_ENV
        
    # Ensure prepare-build script is executable
    - name: Make prepare-build script executable
      run: chmod +x scripts/prepare-build.sh
      
    # Debug: List data directory structure
    - name: List data directory
      run: |
        echo "Data directory contents:"
        ls -la data/trucks/
        
    # Explicit run of prepare-build script
    - name: Run prepare-build script explicitly
      run: |
        npm run prepare-build
        echo "Checking prepare-build results:"
        ls -la src/data/trucks/ || echo "Failed to find src/data/trucks/"
        ls -la components/data/trucks/ || echo "Failed to find components/data/trucks/"
        
    # Build the application
    - name: Build Next.js application
      run: npm run build
    
    # Debug: List output directories
    - name: Check build output
      run: |
        echo "Output directories:"
        ls -la out/
        echo "Components data directory:"
        ls -la components/data/trucks/ || echo "No components/data/trucks directory"
        echo "Src data directory:"
        ls -la src/data/trucks/ || echo "No src/data/trucks directory"
      
    # Добавим файл .nojekyll, чтобы отключить обработку Jekyll
    - name: Create .nojekyll file
      run: touch ./out/.nojekyll
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    # Only deploy on main branch
    if: github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    needs: build
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
