name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Setup environment variables
      run: |
        echo "NEXT_PUBLIC_APP_URL=${{ secrets.NEXT_PUBLIC_APP_URL || 'https://margarita215729.github.io/truck-repair-assistant' }}" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_BASE_PATH=${{ secrets.NEXT_PUBLIC_BASE_PATH || '/truck-repair-assistant' }}" >> $GITHUB_ENV
        echo "NEXT_PUBLIC_NOMINATIM_URL=${{ secrets.NEXT_PUBLIC_NOMINATIM_URL || 'https://nominatim.openstreetmap.org' }}" >> $GITHUB_ENV
        
    # Создаем директорию для скриптов, если она не существует
    - name: Ensure scripts directory exists
      run: mkdir -p scripts
        
    # Создаем скрипт подготовки файлов
    - name: Create prepare-build script
      run: |
        cat > scripts/prepare-build.sh << 'EOL'
        #!/bin/bash
        mkdir -p src/data/trucks
        cp -r data/trucks/* src/data/trucks/ || echo "No model files to copy"
        echo "Project files prepared for build!"
        EOL
        chmod +x scripts/prepare-build.sh
    
    # Запускаем скрипт подготовки файлов
    - name: Run prepare-build script
      run: ./scripts/prepare-build.sh
        
    - name: Build application
      run: npm run build
      
    # Добавим файл .nojekyll, чтобы отключить обработку Jekyll
    - name: Create .nojekyll file
      run: touch ./out/.nojekyll
      
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./out

  deploy:
    # Only deploy on main branch
    if: github.ref == 'refs/heads/main'
    
    runs-on: ubuntu-latest
    needs: build
    
    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
